---
# Instructions for using this template:
# 1. Replace <package_name> below with the short name of the python package.
#    E.g. if the package is bican_mccarroll_mypackage, replace "<package_name>" with "mypackage".
# 2. Name the workflow file python-<package_name>.yml, e.g. python-mypackage.yml
# 3. Commit the above changes
name: "Python unit tests for bican_mccarroll_<package_name>"
"on":
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
    paths:
      - "python/bican_mccarroll_<package_name>/**"


jobs:
  call-python-reusable:
    uses: "./.github/workflows/python-reusable.yml"
    with:
      package_name: "<package_name>"
    secrets: "inherit"
